=== Nadyahaeckaya/project/lab11.xsd
<?xml version="1.0" encoding="UTF-8" ?> 
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
     <xs:element name="countrys"> 
<xs:complexType> 
<xs:sequence> 

	 <xs:element name="country" maxOccurs="unbounded"> <!--Этот элемент может повторяться много раз, без ограничений -->
 <xs:complexType> 
 <xs:sequence>  
     <xs:element name="name" type="xs:string"/> 
     <xs:element name="people" type="xs:string"/> 
</xs:sequence> 
</xs:complexType> 
</xs:element>

</xs:sequence> 
</xs:complexType> 
</xs:element>

</xs:schema>

=== Nadyahaeckaya/project/lab11-3.xml
<?xml version="1.0" encoding="UTF8"?>
<?xml-stylesheet type='text/css' href='style.css'?>
<!-- адрес служит как уникальный идентификатор стандарта XML Schema -->
	<!-- XML‑документ должен проверяться по схеме, которая лежит в файле -->
<countrys 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="lab11.xsd">
<country>
	<name> Индия</name>
	<people>1463865525 человек</people>
</country>
<country>
	<name> Китай</name>
	<people>1416096094 человек</people>
</country>
<country>
	<name> США</name>
	<people>347275807 человек</people>
</country>
<country>
	<name>Россия </name>
	<people>144429000 человек</people>
</country>
</countrys>
